name: aprilplay
description: "A Simple CRUD Music App using Riverpod and Supabase by Me Aprilla 22552011133"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Design ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # Untuk font custom
  sizer: ^3.0.1 # Agar ukuran responsif di berbagai HP

  # --- State Management (Riverpod) ---
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1 # Saya pakai ini untuk fitur hooks jika diperlukan
  riverpod_annotation: ^2.6.1
  flutter_hooks: ^0.20.5

  # --- Backend & Database ---
  supabase_flutter: ^2.8.4 # Database utama

  # --- Features ---
  audioplayers: ^6.0.0 # Untuk memutar musik
  file_picker: ^8.1.4 # Untuk ambil file dari galeri

  # --- Data Models ---
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.5.4
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.5
  freezed: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
